### ISSUE TITLE
Оттоманы

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#102]
Весьма качественный, комплексный мод. Думаю можно кое-что интегрировать.
http://steamcommunity.com/sharedfiles/filedetails/?id=297160686&searchtext=

**Comment by xXxSPYxXx** [comment]
Много переводить

**Comment by MaksDeep** [comment]
Я могу этим заняться.

**Comment by Astarot11** [comment]
Внес правки в перевед, пофиксил вылет. Мод готов к интеграции полностью
