### ISSUE TITLE
Ивент выпадает неверно

### ISSUE THREAD

**Issue by Astarot11** [Feas2016/Russian-Universalis#106]
Всё очевидно. Человек говорит, что решений не принимал, ивент выскакивает по нескольку раз за полгода
![ffhpv0cqcnm](https://cloud.githubusercontent.com/assets/18719214/16361587/bca27edc-3bc7-11e6-93d6-e1495036ff0d.jpg)

**Comment by Feas2016** [comment]
```
country_event = {
	id = stt_greeks_events.4
	title = stt_greeks_events.t.4
	desc = stt_greeks_events.de.4
	picture = NEW_HEIR_eventPicture
	
	major = yes
	is_triggered_only = yes

	option = {
		name = stt_greeks_events.a.4
		add_prestige = -10
		add_legitimacy = -50
		define_heir = {
			dynasty = ROOT
			claim = 20
		}
	}
}
```


`	byz_adopted_heir = {
		major = yes
		potential = {
			OR = {
				tag = BYZ
				tag = ROM
			}
			NOT = { has_ruler_modifier = byz_heir_adopted }
			ai = no
			NOT = { is_year = 1533 }
			has_heir = no
			
		}
		allow = {
			is_lesser_in_union = no
			has_regency = no
			has_heir = no
		}
		effect = {
			add_years_of_income = -1
			add_ruler_modifier = {
				name = "byz_heir_adopted"
				duration = -1
			}
			country_event  = { id = stt_greeks_events.4 }
		}
		ai_will_do = {
			factor = 0
		}
	}`

**Comment by Feas2016** [comment]
других условий нет is_triggered_only = yes означает 100% отсутствие срабатывания эвента по триггеру.
