### ISSUE TITLE
баги

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#110]
![eu4_20](https://cloud.githubusercontent.com/assets/18704326/16449198/a31fa6b8-3dfe-11e6-9c5d-f784017b010f.png)
Описание: не правильно переведена синайская пустыня. Скажите где исправить-исправлю.
![i9 cimgpsh_orig](https://cloud.githubusercontent.com/assets/18704326/16449213/bf59947e-3dfe-11e6-9c91-fc636925a1ac.jpg)
Как видно на скрине, Мид вместо того чтоб быть включённым - просто оккупирован, хотя Британия и не воюет с ним, т.е. это баг.

**Comment by MaksDeep** [comment]
![eu4_20](https://cloud.githubusercontent.com/assets/18704326/16449198/a31fa6b8-3dfe-11e6-9c5d-f784017b010f.png)

![i9 cimgpsh_orig](https://cloud.githubusercontent.com/assets/18704326/16449213/bf59947e-3dfe-11e6-9c91-fc636925a1ac.jpg)

**Comment by xXxSPYxXx** [comment]
Добавь описание хоть

**Comment by Feas2016** [comment]
исправил
