### ISSUE TITLE
интеграция мода East Asian Advisor Portraits

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#114]
http://steamcommunity.com/sharedfiles/filedetails/?id=679184877
думаю все видели этот мод. Я уверен что его стоило бы включить в РУ. Всякие Монглолы и Тюрксие каганаты будут счастливы))

upd: автор дал своё согласие (в стиме)

**Comment by Feas2016** [comment]
Лан, а как насчет европейских?

**Comment by Feas2016** [comment]
можно сделать и на восточный тех к слову)

**Comment by MaksDeep** [comment]
идея то хороша. Но данный мод реально шедеврален. А налогов такого же качества на Русь, Я не видел

**Comment by Feas2016** [comment]
https://github.com/Feas2016/Russian-Universalis/issues/136
