### ISSUE TITLE
Гвардия

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#128]
Не знаю насколько это вообще реализуемо, но появилась идея, что можно было бы при наличии определённых пров и постройке спец зданий создавать элитный тип войск у которого параметры будут выше чем у текущих войск вне зависимости от уровня технологий. Соотношение лимита армии 10К к 1К гвардии выглядит вполне разумным. У гвардии не будет каких-то имбовских параметров, но всё же они будут лучше чем текущие войска. 
У большинства стран гвардия будет пехотой. у немногих кавалерией, и совсем небольшого кол-ва стран - артиллерия.

**Comment by Feas2016** [comment]
Прикольно, но увы - все привязано к окну выбора типа войск или наемникам, которые тоже зависят от первого.

**Comment by MaksDeep** [comment]
ну так а если они будут автоматически появляться, по ивенту?

**Comment by Feas2016** [comment]
спавн возможен только имеющихся юнитов.

**Comment by MaksDeep** [comment]
жаль ну тогда закрываю
