### ISSUE TITLE
Лоди и Днестр

### ISSUE THREAD

**Issue by xaaxaaxaa** [Feas2016/Russian-Universalis#132]
Это я, Яков. Я сделал две провки. 
Ссылка на файл: http://rgho.st/7bb5tL9F9
Пароль: коза
Скинул на ргхост из-за того, что файлы весят 17 мегабайт, а исходник вообще 132.

**Comment by Feas2016** [comment]
https://github.com/Feas2016/Russian-Universalis/issues/137
