### ISSUE TITLE
и снова Славия

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#134]
Мне кажется в условия создания нужно добавить контроль над такими провами как София(Болгария), Прага(Чехия), Лужица(Лужицкие Сербы), Морвия, Данциг(можно вместо Варшавы), ну и Полоцк(Беларусь).
Это нужно для того чтобы показать объединение именно ВСЕХ славян а не только Сербов, Поляков и Русских.

**Comment by Feas2016** [comment]
перенесено в тему багов
