### ISSUE TITLE
Здания открыты с начала игры

### ISSUE THREAD

**Issue by ShurfL** [Feas2016/Russian-Universalis#178]
![default](https://cloud.githubusercontent.com/assets/28927532/26409539/9d416642-40c2-11e7-8a96-561b50926a8b.png)

**Comment by xXxSPYxXx** [comment]
О проблеме знаем, ждем фикса. Спасибо за баг-репорт.

**Comment by Astarot11** [comment]
Пофиксили, закрыть можно
