### ISSUE TITLE
Каспийское море

### ISSUE THREAD

**Issue by Feas2016** [Feas2016/Russian-Universalis#25]
Общая тема: http://www.strategium.ru/forum/index.php?showtopic=79215&st=0
![f43b916e479a](https://cloud.githubusercontent.com/assets/13850023/14860665/90a29810-0cb2-11e6-874e-afc77d702b09.png)
![4664f109f7bb](https://cloud.githubusercontent.com/assets/13850023/14860737/c3c096fc-0cb2-11e6-830b-a49d7458e4b9.png)

Само море и переправы интересуют инициаторов в первую очередь.
Голосование решило так 3 против, 1 за 1 воздержался.
Причины: будущие жалобы на глупого ИИ и отсутствие особой пользы от данного изменения.

Стоит заглянуть в этрус.

**Comment by Feas2016** [comment]
В этрусе только море, без канала
![zjl7thx](https://cloud.githubusercontent.com/assets/13850023/14861779/5bd28c44-0cb7-11e6-8700-89ce1f33ad64.png)

**Comment by MaksDeep** [comment]
Я наверное, тот что за?))

**Comment by Feas2016** [comment]
![zjl7thx](http://i.imgur.com/F3ZT1CX.png)
