### ISSUE TITLE
Десмонд - вылет.

### ISSUE THREAD

**Issue by Feas2016** [Feas2016/Russian-Universalis#31]
Как повторить: запускаем игру за любую страну, выбираем провинцию Десмонд.

**Comment by Feas2016** [comment]
Закончил с ними, но при нажатии на провку Десмонда происходит вылет.

**Comment by Astarot11** [comment]
У меня вылета нет
![ewao2vwcraq](https://cloud.githubusercontent.com/assets/18719214/15778335/16cc4ca6-29c8-11e6-91b8-64eebbbe2512.jpg)

**Comment by Feas2016** [comment]
Как повторить: запускаем игру за любую страну, выбираем провинцию Десмонд.

**Comment by Astarot11** [comment]
Вот блин) Ага, действительно вылет

**Comment by Feas2016** [comment]
Логи: 
######## EXCEPTION: 0xC0000005 at address: 0x014DB329: ACCESS VIOLATION  read attempt to address 0x00000000 
Version: Unknown Version
06/02/16 21:26:19


######## EXCEPTION: 0xC0000005 at address: 0x0044B329: ACCESS VIOLATION  read attempt to address 0x00000000 
Version: Unknown Version
06/06/16 18:12:45


######## EXCEPTION: 0xC0000005 at address: 0x00CDB329: ACCESS VIOLATION  read attempt to address 0x00000000 
Version: Unknown Version
06/06/16 18:47:58

Error.log, Validator тоже не видят проблемы в истории провы, самой карте касательно данной провинции.
История провы читается, это видно из карт товаров например, торговли, местности и всех остальных.
Внешне проблем тоже нет.
Пробовал менять цвет в provinces.bmp толку никакого.
![20160606183306_1](https://cloud.githubusercontent.com/assets/13850023/15829257/9eaff5aa-2c1b-11e6-98e9-361ad5c6bdca.jpg)

Боюсь идей больше нет.

**Comment by Feas2016** [comment]
![20160606192713_1](https://cloud.githubusercontent.com/assets/13850023/15829514/c9128032-2c1c-11e6-85e8-355c3a05e6a3.jpg)
