### ISSUE TITLE
Интеграция building mod

### ISSUE THREAD

**Issue by xXxSPYxXx** [Feas2016/Russian-Universalis#34]
http://www.strategium.ru/forum/index.php?showtopic=79284
Возможно сделать под модом?

**Comment by Feas2016** [comment]
Разрешение есть от автора, можно добавлять.

**Comment by MaksDeep** [comment]
А что планируется интегрировать то? Потому, что имхо у него в моде много лишнего.

**Comment by Feas2016** [comment]
Я мод ставил, там есть:

- графика
- новые строения
- гетьманщина
- сценарии
- советники
- доп. технология и 2 строки идей (наверное опущу до 1356 мода)

Вроде неплохо.

**Comment by MaksDeep** [comment]
всё одобряю, вот только к графике у меня вопросы.По тем скринам что Я видел, в окне результатов боя фон для юнитов имхо отвратный и не вписывается вообще. В таком же окне для морских сражений одинаковые картинки для кораблей, хотя сражаются могут корабли евро теха и азиатского например.
И насчёт Гетьманщины Я не совсем понял что именно добавляется.

**Comment by Feas2016** [comment]
Все авторы мелких стран, особенно ВКЛ стараются освободить подконтрольные силы и княжества как та самая Гетьманщина.

**Comment by MaksDeep** [comment]
а зачем?
