### ISSUE TITLE
Ошибки с провинциями из 1.16

### ISSUE THREAD

**Issue by Astarot11** [Feas2016/Russian-Universalis#36]
Немного багов (возможно что-то пофиксено уже, но на всякий случай)

1-ый скрин: баг с названием провы
2. Повстанцы есть, но отрядов их нет
3. Уничтоженный Одоев дипломатически активен
4. Анимизм (скрин не мой, я его даж тут не вижу, но мало ли)
5. Грузинские сепары в Крыму

Также сообщиили, что невозможно колонизировать провинции с базовыми значениями, находящимися на нуле. Т.е базовый набор рекрутов, налог, пр-во. Пишет мол слишком плохие условия для колонизации

![2](https://cloud.githubusercontent.com/assets/18719214/15453107/a3f2577a-203a-11e6-8a0c-525fbed594cd.jpg)
![3](https://cloud.githubusercontent.com/assets/18719214/15453108/ade63602-203a-11e6-88a0-fe1dc940b704.jpg)
![4](https://cloud.githubusercontent.com/assets/18719214/15453109/af735464-203a-11e6-8a85-c4f9c5ef8214.jpg)
![5](https://cloud.githubusercontent.com/assets/18719214/15453110/b1b5a952-203a-11e6-8ee9-b0fb51373ecd.jpg)
![6](https://cloud.githubusercontent.com/assets/18719214/15453111/b36b4e64-203a-11e6-97d6-78119ac2931a.jpg)

**Comment by xXxSPYxXx** [comment]
1-3 это все баг новых провинций патча 1.16.
4- пофиксим (относится к 1-3)
5 - это вроде нормально.

**Comment by Feas2016** [comment]
![20160524223220_1](https://cloud.githubusercontent.com/assets/13850023/15517287/aff47cbc-21ff-11e6-854a-f7ac97146261.jpg)

**Comment by Feas2016** [comment]
[23:07:55 | Изменены 23:08:11] Александр(FEAS): Игра почему-то не видит команды: replace_path="history/provinces" потому считает что данные из оригинальной папки актуальны.
[23:08:25 | Изменены 23:08:36] Александр(FEAS): Пришлось их добавить в мод пустыми, чтоб игра не визжала
