### ISSUE TITLE
Два Томонда

### ISSUE THREAD

**Issue by Astarot11** [Feas2016/Russian-Universalis#39]
Обнаружил, что в игре два Томонда. Наверно с переводом баг. Теги стран на скринах. Который юго-западнее использует томондские идеи, второй ирландские.
![eu4_36](https://cloud.githubusercontent.com/assets/18719214/15536700/1ce49104-22a5-11e6-8171-67f7f46161d3.jpg)
![eu4_37](https://cloud.githubusercontent.com/assets/18719214/15536704/23471d32-22a5-11e6-96ed-a7553e8d3f31.jpg)

**Comment by Feas2016** [comment]
![20160602193308_1](https://cloud.githubusercontent.com/assets/13850023/15753263/d725ffac-28fa-11e6-8310-06dfd1d63402.jpg)
