### ISSUE TITLE
Ошибки (недоработки) с типами местности

### ISSUE THREAD

**Issue by Astarot11** [Feas2016/Russian-Universalis#40]
Если коротко, то типы местности некоторых пров не соответствуют реальности. Луга на севере Канады, например. Еще северная прова в Гренландии. Тип местности побережье, еще и мягкая зима. Также возникают ошибки с изображениями северных пустошей. Тип местности такой, модификатор есть, но картинка может быть степная или лесная. Все пояснения есть на скринах.
![eu4_4](https://cloud.githubusercontent.com/assets/18719214/15537599/0341d3ba-22aa-11e6-82dc-4a0f1196b322.jpg)
![eu4_3](https://cloud.githubusercontent.com/assets/18719214/15537600/04bb617a-22aa-11e6-9a70-1099a3c8908a.jpg)
![eu4_2](https://cloud.githubusercontent.com/assets/18719214/15537601/05cc5f42-22aa-11e6-9b93-a297db2f759c.jpg)
![eu4_1](https://cloud.githubusercontent.com/assets/18719214/15537602/06e20b16-22aa-11e6-9943-fb377c080ff1.jpg)
![eu4_5](https://cloud.githubusercontent.com/assets/18719214/15537604/08c8165a-22aa-11e6-985f-5ec015369e8a.jpg)

**Comment by Feas2016** [comment]
Нет картинки с ледяными пустошами/неверный адрес на картинку, ясно.

**Comment by Feas2016** [comment]
![eu4_45](http://i.imgur.com/aQcjfnU.png)

картинку местности починил, но все равно нужен пересмотр местностей и картинок примитивных цивилизаций.

**Comment by Feas2016** [comment]
На данный момент поправлен климат, но не местность. Карта "упрощенная местность" в помощь.
![20160606214709_1](https://cloud.githubusercontent.com/assets/13850023/15833625/599bfb52-2c30-11e6-8b19-f52c2ccf5059.jpg)
![20160606214705_1](https://cloud.githubusercontent.com/assets/13850023/15833624/599a0b26-2c30-11e6-85cd-6c9f3ac18eaf.jpg)
![20160606214700_1](https://cloud.githubusercontent.com/assets/13850023/15833623/59954672-2c30-11e6-999c-4374bad559b9.jpg)
![20160606214612_1](https://cloud.githubusercontent.com/assets/13850023/15833627/599e7c60-2c30-11e6-9c35-255b49e372fe.jpg)
![20160606214540_1](https://cloud.githubusercontent.com/assets/13850023/15833626/599ce22e-2c30-11e6-8dca-8e6158c1dd31.jpg)

**Comment by Astarot11** [comment]
Мною климат же и поправлен, хехехе. Сегодня займусь типами местности, окей
