### ISSUE TITLE
Вылеты при более поздних стартах

### ISSUE THREAD

**Issue by Astarot11** [Feas2016/Russian-Universalis#41]
Сообщают, что при старте на любой дате, позднее начальной, игра после пяти дней вылетает (зависает).

**Comment by Feas2016** [comment]
exceptions.txt из логов нужен.

**Comment by Feas2016** [comment]
######## EXCEPTION: 0xC0000005 at address: 0x019B85E1: ACCESS VIOLATION  read attempt to address 0x00000000 
Version: Unknown Version
05/27/16 12:03:02


Это точно полный лог?

**Comment by Feas2016** [comment]
![20160531122530_1](https://cloud.githubusercontent.com/assets/13850023/15669835/fba07bd6-272a-11e6-8f38-5d4994610f31.jpg)

2 месяца - вылета нет.

**Comment by Astarot11** [comment]
Больше не встречаю вылетов на поздних стартах, закрываю
