### ISSUE TITLE
Казаки немного не там

### ISSUE THREAD

**Issue by Astarot11** [Feas2016/Russian-Universalis#44]
Скрин всё объяснит
![eu4_3](https://cloud.githubusercontent.com/assets/18719214/15653582/6ffa9f5e-26c0-11e6-9cdc-a90bad3d7255.png)

**Comment by Feas2016** [comment]
=))))) Тег совпал.

**Comment by Feas2016** [comment]
![20160602204936_1](https://cloud.githubusercontent.com/assets/13850023/15755452/892625e2-2905-11e6-8e82-f0341f1d413b.jpg)
