### ISSUE TITLE
Колонизация незаселенных провинций Скандинавии

### ISSUE THREAD

**Issue by xXxSPYxXx** [Feas2016/Russian-Universalis#45]
Нужно написать Ивенты на колонизацию этих провинций. Потом ивент на смену культуру и добавление корок (Финляндии или еще какой страны). Нужно сверить с историей.

**Comment by Feas2016** [comment]
![eu4_157](http://i.imgur.com/YOZsYnp.png)
http://geacron.com/home-en/

**Comment by Feas2016** [comment]
![20160602195114_1](https://cloud.githubusercontent.com/assets/13850023/15753399/806be626-28fb-11e6-88d3-865d4098398f.jpg)
![20160602195059_1](https://cloud.githubusercontent.com/assets/13850023/15753398/806bac88-28fb-11e6-87dd-91d380c0d984.jpg)

**Comment by Feas2016** [comment]
Сельма Жескова
Постоянно выскакивает ивент на заселение Лапландии, даже если играешь в более поздний сценарий, когда она заселена давно.
Мне нравится
два часа назад
Александр Власов
Наверно стоит прописать условие, чтобы прокал ивент только когда прова пустая. Скажу об этом. Или сам сделаю, если разберусь
Мне нравится
час назад|Ответить
Александр Власов
А остальные провы тоже заселены? Их 3 всего пустые
Мне нравится
час назад|Ответить
Сельма Жескова
Мне кажется, что к 1600 там все заселено, пустот я там не заметила.
Мне нравится
1
час назад Александру|Ответить
Александр Власов
Сельма, если бы они были, то заметила бы) Немалые провы. Окей
Мне нравится
час назад Сельме|Ответить

**Comment by Astarot11** [comment]
Я посмотрел, поковырял ивент, но так и не понял в чем причина. Держи скрин, когда колонии уже стоят, ивент все равно у скандинавских стран прокает
![eu4_21](https://cloud.githubusercontent.com/assets/18719214/15783551/346a2684-29e1-11e6-9763-1c07954d24ea.png)

**Comment by Feas2016** [comment]
добавил is colony - помогает?

**Comment by Astarot11** [comment]
Сделал пул-реквест фиксящий, однако предлагаю все же при проке ивента полностью заселять прову. Без колониста слишком большие расходы на колонию. Заселяться она без идей будет примерно 7 лет. Игроку тяжело, а ИИ вообще отказывается от колонии потом.

**Comment by MaksDeep** [comment]
Имхо, тоже нужно по ивенту. Сразу заселять.

**Comment by xXxSPYxXx** [comment]
@Feas2016 
Когда ивент выскакивает, бот уменьшает содержание колонии до 0 и она сразу пропадает (скорей всего из-за того, что нет колонистов и соответственно не выбрана политика колоний).

**Comment by Feas2016** [comment]
было 900 чел стало 1000
