### ISSUE TITLE
Правка провинций

### ISSUE THREAD

**Issue by xXxSPYxXx** [Feas2016/Russian-Universalis#46]
Армия не может напрямую перейти в соседнюю провинцию.
![eu4_157](https://cloud.githubusercontent.com/assets/3036903/15706820/2f0479a4-27fe-11e6-9daa-b866cf1e14dd.png)

**Comment by Feas2016** [comment]
Что забавно:
![20160602173646_1](https://cloud.githubusercontent.com/assets/13850023/15748751/b07cfed0-28e8-11e6-9f9d-6d694cd17ca7.jpg)
Обратно идут

**Comment by Feas2016** [comment]
![20160602194644_1](https://cloud.githubusercontent.com/assets/13850023/15753296/f823a254-28fa-11e6-9b1c-55516f7f6b9c.jpg)
