### ISSUE TITLE
Эвент, изменить на "нет культуры"

### ISSUE THREAD

**Issue by Feas2016** [Feas2016/Russian-Universalis#48]
![screenshot_5](https://cloud.githubusercontent.com/assets/13850023/15750431/1bf403ba-28ef-11e6-9e8f-2752ad797bca.png)

**Comment by xXxSPYxXx** [comment]
![eu4_158](https://cloud.githubusercontent.com/assets/3036903/15783767/34dc458a-29b8-11e6-88e0-9f1db3152bc8.png)

**Comment by Feas2016** [comment]
Татарские страны снова со своей культурой, забыл откатить.

**Comment by Feas2016** [comment]
![screenshot_7](https://cloud.githubusercontent.com/assets/13850023/15791651/4dbf9bb4-29e1-11e6-9a15-aeec304bf023.png)
