### ISSUE TITLE
Казач(цк)ий вопрос

### ISSUE THREAD

**Issue by Astarot11** [Feas2016/Russian-Universalis#60]
Цитирую Maksim Deep; Тогда у меня следующие предложения. Создать Терских казаков. Яицких переименовать в Уральских.

**Comment by MaksDeep** [comment]
По поводу Терских казаков. Это третье по старшинству казачье Войско, после Уральского. Играло большую роль в освоении Кавказа и всех последующих кавказских конфликтах. В частности играли большую роль в войнах с Персией. По некоторых данные на начало ХХ века численность была до 500К, что немало. 
Если идея найдёт отклик, могу поработать над идеями ну и флагом естественно. Так же введение этого казачьего государства подразумевает создание доп провинций на Кавказе но это уже позже.
А по поводу Яицких, тут всё просто. Одинаково правильно их называть и Уральскими и Яицкими(в честь реки Яик, на которой было основано первое поселение), но многие игроки которые не читали про казаков, не поймут о ком речь. Ну и наконец, имхо Уральские звучит лучше, чем Яицкие.
