### ISSUE TITLE
Военно-монашеские ордена и Казачества

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#61]
Хотелось бы, чтобы Ордена и Казаки будучи вассалами, не занимали очков дипломатии, а были реализованы типа колоний с которыми есть дип отношения, но дип очки на них не тратятся. Это позволяло бы иметь несколько миноров -вассалов, и не присоединять их только для того, чтоб экономить дип очки.

**Comment by Feas2016** [comment]
к сожалению игра остановится, если добавить любым путем дип слоты. 2-х было достаточно чтоб ИИ перестал воевать друг с другом.

**Comment by Astarot11** [comment]
В свое время я об этом и сообщил, хехех. Ностальгия аж немного прибрала

**Comment by MaksDeep** [comment]
а как же колонии?

**Comment by Feas2016** [comment]
Сожалению, но кода на создания колонии или кода на переделки страну в колонию у меня нет. Делать из Золотой орды колонию будет слишком =))))

**Comment by MaksDeep** [comment]
ну да, Я понял. можно закрывать тему.

**Comment by Feas2016** [comment]
для них есть марки, тема закрыта.
