### ISSUE TITLE
 Африканская казачья экспедиции Николая Ашинова

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#63]
вдохновил на поиски по данной теме баг об уральских казаках в африке. А оказывается там и правда были такие, только терские казаки.Итак сам ивент:
Африканская казачья экспедиции Николая Ашинова. Она по времени не подходит, она была в 1888 году. Но по ивенту можно и раньше сделать. Суть в том, что в Джибути появляется русская колония. Название колонии Новая Москва, но мне больше нравится Станица Московская 
Условия могут быть такими например: 
+50 отношения с Абиссинией.
Наличие Французских колоний в Африке
Наличие Английских колоний в Африке
Терское Казачество существует
В случае принятия ивента: 
Колония в Джибути (можно спецом на карте доп. прову даже нарисовать)
Союз с Абиссинией
отношения +200
гарантия независимости Абиссинии (Эфиопии) со стороны России 
отношения с Англией -100
Отношения с Францией -150 и/или война
пруф:
http://www.vokrugsveta.com/S4/proshloe/ashinov.htm

**Comment by Feas2016** [comment]
Ватники очень любят такие идеи, стоит реализовать, я за.

**Comment by MaksDeep** [comment]
мы ватники такие)

**Comment by Feas2016** [comment]
представь удивление непосвященного =)
