### ISSUE TITLE
Эфиопия - Абиссиния

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#64]
Так как мод всё таки русский и основной акцент в нём на восточную Европу и Россию, то предлагаю переименовать Эфиопию в Абиссинию, как она называлась на Руси, имхо предаст историчности и антуража

**Comment by Astarot11** [comment]
Кинь, плиз, пруф насчет того, что Эфиопия = Абиссиния с точки зрения русского языка. Над читнуть. Потом наверно переименую сам

**Comment by MaksDeep** [comment]
https://ru.wikipedia.org/wiki/%D0%AD%D1%84%D0%B8%D0%BE%D0%BF%D0%B8%D1%8F#.D0.9D.D0.B0.D0.B7.D0.B2.D0.B0.D0.BD.D0.B8.D0.B5

**Comment by Astarot11** [comment]
Можно закрывать, я скинул файлы в скайп на локализацию
