### ISSUE TITLE
Один большой список багов. 

### ISSUE THREAD

**Issue by Astarot11** [Feas2016/Russian-Universalis#71]
2) Провинция в Саксонии Айзенах принадлежит узлу Северное море 
3) Во многих провах европы арктический климат, когда его там быть не должно. И не только европы. Климатическая карта отвратительная в Сибири. То место, где я родился и вырос помечено как прова с арктическим климатом. Это же беспредел, у нас резко-континентальный климат, тип умеренного, жизнь процветает. Короче собираюсь переделывать это безобразие на основе объективных климатических данных. Да и колонить Сибирь (по крайней мере южную часть) будет проще.
![vks765nuuz8](https://cloud.githubusercontent.com/assets/18719214/15804134/1debbaa2-2b31-11e6-878d-20af914c2b16.jpg)
![-m4xhbjvs5a](https://cloud.githubusercontent.com/assets/18719214/15804135/1eec6ce4-2b31-11e6-9ee6-e5c3ee6279a9.jpg)

**Comment by MaksDeep** [comment]
Насчёт Франции, Пиреней, Карпат и Балкан - это 100% лажа - надо убрать.
