### ISSUE TITLE
Баг Юго-восточная Азия

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#74]
![2](https://cloud.githubusercontent.com/assets/18704326/15806664/09c02bb0-2b51-11e6-85ce-9de516dae530.jpg)
![default](https://cloud.githubusercontent.com/assets/18704326/15806665/09c1b656-2b51-11e6-81c5-d93a0f2e970d.jpg)

**Comment by Feas2016** [comment]
![20160606203211_1](https://cloud.githubusercontent.com/assets/13850023/15831341/d3c237e4-2c25-11e6-8900-bd1e83c011b6.jpg)
![20160606203217_1](https://cloud.githubusercontent.com/assets/13850023/15831342/d3c3c064-2c25-11e6-9571-6b4156ebbe0f.jpg)
