### ISSUE TITLE
Сценарии Литва - Москва

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#75]
![i5 cimgpsh_orig](https://cloud.githubusercontent.com/assets/18704326/15806688/ad7a920e-2b51-11e6-8599-f4b26e8ae5f4.png)

**Comment by Feas2016** [comment]
обе провки починены

Сценарий 1585 (и дальше) - Витебск точно не в России.
У Литвы претензии - Великие Луки, Торопец, Дорогобуж, Смоленск, Ельня, Брянск, Стародуб, Чернигов, Севершина. Но уже не Вязьма. Не до того было.
В смысле, это уже претензии РП, но наследованы они от ВКЛ.
