### ISSUE TITLE
Карта Пустошей Северной Америки и южной Африки

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#76]
![3](https://cloud.githubusercontent.com/assets/18704326/15806729/28b05a98-2b53-11e6-943c-0465dd262c6c.jpg)
![default](https://cloud.githubusercontent.com/assets/18704326/15806730/28b447f2-2b53-11e6-8fb7-38084c16b033.jpg)
Мне кажется что вот такие угловаты пустоши это не очень. Ладно провы в Америке, Феасу их все переделывать в лом, но пустоши то хотя бы надо сделать  аккуратными. Кто как думает?

**Comment by Feas2016** [comment]
Причина проста, европейцы туда доехали только ко 2-й половине 19 века и просто поделили неизвестную территорию.

[1](https://upload.wikimedia.org/wikipedia/commons/5/56/Greatbasinmap.png)
[2](https://upload.wikimedia.org/wikipedia/commons/3/36/Namibia%2C_administrative_divisions_-_Nmbrs_-_colored.svg)

**Comment by MaksDeep** [comment]
да Я понимаю, просто меня аж типает от этого) Я настолько привык "округлым" провам что это аж глаз режет)

**Comment by Feas2016** [comment]
*тут должна быть картинка округлых форм* XD

**Comment by MaksDeep** [comment]
мне полегчало)))
