### ISSUE TITLE
Терские казаки и переименование Яицких

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#77]
Предлагаю создать Терских казаков.
Терские казаки это 3-е казачье войско. Принимали самое деятельное участие в освоении Россией Кавказа, подавлении бунтов, войне с Турцией и Персией.
к XIX веку численность была более 500K
нужно будет добавить пару тройку доп пров на Кавказе.
Идеи и пару ивентов могу написать ну и флаг естественно)

По поводу Яицких казаков это исторично, но у них точно такое же признанное название - Уральские казаки. + всем будет понятно где они и что они делали. + имхо так гораздо лучше звучит

**Comment by Feas2016** [comment]
с 1584 года по 1775 год и после 1917 года всеж Яицкие.

А вот за Терских я только за.

**Comment by MaksDeep** [comment]
Отлично. Думаю надо будет добавить пару-тройку пров на Кавказе, Феас сможешь? А Я над идеями подумаю, мб ивенты  как-нибудь придумаю

**Comment by Feas2016** [comment]
без проблем.

**Comment by Feas2016** [comment]
https://github.com/Feas2016/Russian-Universalis/issues/99
