### ISSUE TITLE
2.0 The World is complete

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#83]
Интересный мод, думаю Феасу (как картоделу) будет интересно посомотреть.
http://steamcommunity.com/sharedfiles/filedetails/?id=455775980&searchtext=Jan+Mayen

**Comment by xXxSPYxXx** [comment]
Мы карту уже сделали, не думаю что будет опять заниматься адаптацией.

**Comment by MaksDeep** [comment]
Я ж поэтому и написал "посмотреть". Просто может какую идею на будущее почерпнёт)

**Comment by Feas2016** [comment]
Точно нет, особо долго не рассматривал ибо играбельности там никакой.
Подробнее: http://www.strategium.ru/forum/index.php?showtopic=60825
