### ISSUE TITLE
Вылет при создании Триединого народа

### ISSUE THREAD

**Issue by Astarot11** [Feas2016/Russian-Universalis#87]
При игре за РП, во время бедствия, появляется ивент с кракозябрами и тут же происходит вылет

**Comment by xXxSPYxXx** [comment]
Нужны логи.
https://github.com/Feas2016/Russian-Universalis/wiki/%D0%96%D0%B5%D0%BB%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B4%D0%BB%D1%8F-%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B1%D0%B0%D0%B3%D0%B0

**Comment by Feas2016** [comment]
https://github.com/Feas2016/Russian-Universalis/commit/ca15797646cb8062f35d0e97e9a4cd0fdb52b683
