### ISSUE TITLE
Набор багов

### ISSUE THREAD

**Issue by xXxSPYxXx** [Feas2016/Russian-Universalis#90]
Мне выпал ивент, который понижает желание свободны у другого униата.
![eu4_171](https://cloud.githubusercontent.com/assets/3036903/15927626/6ce0af92-2e4b-11e6-88c1-039b76c63a12.png)

Тут баг схожий с Казанью, проход на остров не через ту провинцию
![eu4_168](https://cloud.githubusercontent.com/assets/3036903/15927625/6ce0a8c6-2e4b-11e6-9d9a-2939445d18d0.png)

У Австрии правителя зовут Матвей, думаю ошибка в переводе правителей.
![eu4_169](https://cloud.githubusercontent.com/assets/3036903/15927628/6ce1a0dc-2e4b-11e6-8f37-a30a3dbd38dd.png)

Еще остались провинции с системой колонизации мода на карту.
![eu4_170](https://cloud.githubusercontent.com/assets/3036903/15927627/6ce14eac-2e4b-11e6-9fab-45a07a16c381.png)

**Comment by Feas2016** [comment]
1) subject_interaction_events - баг ванили, мне бы номер эвента
2) ок
3) подтверждена
	"Friedrich #4" = 20
	"Franz #0 Stefan" = 20
	"Ladislav #0" = 20
	"Matthias #0" = 20
	"Leopold #7 Johann" = 15
	"Ernst #1" = 15
4) в скайпе

**Comment by Feas2016** [comment]
все кроме 1-ого исправлены
