### ISSUE TITLE
Колонизация лапландии

### ISSUE THREAD

**Issue by xXxSPYxXx** [Feas2016/Russian-Universalis#92]
Необходимо из ивента убрать Данию и оставить только Швецию и Норвегию.
![eu4_172](https://cloud.githubusercontent.com/assets/3036903/15928217/54b91ee2-2e4e-11e6-9da0-23b4e5dcf68b.png)

**Comment by Feas2016** [comment]
Мда, грубую ошибку я допустил, исправил.
