### ISSUE TITLE
О морских переправах

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#96]
Предлагаю рассмотреть вопрос об отмене морских переправ(в дальнейшем МП) в целом. Мои аргументы следующие:
1) Оправдывает наличие и развитие флота.
2) Историчность
3) Реалистичность боёв на островах
Если вы со мной не согласны, пожалуйста аргументируйте.
Или тогда давайте не мелочится и сделаем МП между Эстонией и Финляндией, Австралией и Индокитаем, Францией и Англией наконец. а то не честно как-то наличие МП между Ирландией и Шотландией, а между Францией и Англией нет.

**Comment by Feas2016** [comment]
https://github.com/Feas2016/Russian-Universalis/issues/91
