### ISSUE TITLE
Корявый перевод торговых модификаторов

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#97]
Собственно вопрос, в том, что в данном контексте означает этот модификатор в провинциях.

**Comment by xXxSPYxXx** [comment]
То, что в провинции находится устье реки и оно предпочтительнее для торговли.

**Comment by MaksDeep** [comment]
а предпочтительный торговый центр?

**Comment by xXxSPYxXx** [comment]
Это особенности уже мода на карту.

**Comment by MaksDeep** [comment]
а переименовать это нельзя как то?

**Comment by Feas2016** [comment]
Можно, вот полный список модификаторов:

STT_E\common\event_modifiers\HAB_event_modifiers

**Comment by MaksDeep** [comment]
ну так это ж сами модификаторы а не перевод. Тем более, в английском как раз таки без "предпочтительных"

**Comment by Feas2016** [comment]
хмм... изменил так
 minor_river_estuary_modifier: "Незначительное устье реки"
 major_river_estuary_modifier: "Важное устье реки"
 minor_coastal_center_of_trade_modifier: "Незначительный морской центр торговли"
 major_coastal_center_of_trade_modifier: "Важный морской центр торговли"
 minor_inland_center_of_trade_modifier: "Незначительный сухопутный центр торговли"
 major_inland_center_of_trade_modifier: "Важный сухопутный центр торговли"
