### ISSUE TITLE
Киликия

### ISSUE THREAD

**Issue by MaksDeep** [Feas2016/Russian-Universalis#98]
Предлагаю немного изменить армянскую культуру. Дело в том, что насколько Я знаю, в Киликии в те времена, основная масса населения были всё ещё армяне, а вот из юго-восточных регионов Рума (заштрихованные) они были вынуждены мигрировать (те, которых не поубивали) из-за большого кол-ва тюрков, да и вообще проходной двор там получался)
![1](https://cloud.githubusercontent.com/assets/18704326/15989171/61f29e32-3077-11e6-8c32-1ece27afd467.png)

**Comment by Feas2016** [comment]
Арабкир был одним из центров армянской письменности, в XV—XVII веках здесь был создан ряд рукописей, из которых до нас дошли произведения 1446 и 1640 годов.[1]

В XIX веке в Арабкире получает большое развитие промышленность, особенно льняная, и торговля.[1]

Армянское население дважды (в 1896—1895 и 1915) переживало резню со стороны турецких властей.[1]

**Comment by Feas2016** [comment]
добавил культуры.
